name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main # faqat main branch ga push bo'lsa ishga tushadi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v3

      - name: Docker image yaratish
        run: docker build -t my-nest-app .

      - name: Docker Hub ga kirish
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker Hub ga push qilish
        run: docker tag my-nest-app ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest && docker push ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Serverga SSH orqali ulanib, yangi versiyani yuklash
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker stop my-nest-app || true
            docker rm my-nest-app || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest
            docker run -d --name my-nest-app -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-nest-app:latest
